known_indices_dict = {
    "abundance index": [r"\babundance index\b", r"\babundance indices\b", r"\bindices of abundance\b"],
    "acoustic indices": [r"\bacoustic indices\b", r"\bacoustic index\b", r"\bacoustic based index\b", r"\banimal acoustic indices\b"],
    "aerosol index": [r"\baerosol index\b", r"\baerosol indices\b"],
    "anln (anthropogenic nightlight and noise) risk indices": [r"\banln risk indices\b", r"\banln risk index\b"],
    "anthocyanin indices": [r"\banthocyanin reflectance index\b", r"\banthocyanin reflectance indices\b", r"\banthocyanin and carotenoid indices\b", r"\banthocyanin and carotenoid index\b", r"\banthocyanin reflectance index\b",r"\bmodified anthocyanin reflectance index\b", r"\bmodified anthocyanin reflectance indices\b"],
    "atmospherically resistant vegetation index": [r"\batmospherically resistant vegetation index\b", r"\batmospherically resistant vegetation indices\b"],
    "avian diversity indices": [r"\bavian diversity indices\b", r"\bavian diversity index\b", r"\bavian guild richness indices\b", r"\bavian indices\b"],
    "biodiversity intactness index": [r"\bbiodiversity intactness\b", r"\bbiodiversity intactness index\b", r"\bbiodiversity intactness indices\b"],
    "bird friendliness index": [r"\bbird friendliness index\b", r"\bbird friendliness indices\b"],
    "blade area index": [r"\bblade area index\b", r"\bblade area indices\b"],
    "boyce index": [r"\bboyce index\b", r"\bboyce indices\b"],
    "bray curtis index": [r"\bbray curtis index\b", r"\bbray curtis indices\b", r"\bbray curtis dissimilarity index\b", r"\bbray curtis dissimilarity\b"],
    "canopy leaf area index": [r"\bcanopy leaf area index\b", r"\bcanopy leaf area indices\b"],
    "chlorophyll carotenoid index": [r"\bchlorophyll carotenoid index\b", r"\bchlorophyll carotenoid indices\b"],
    "chlorophyll index red edge": [r"\bchlorophyll index red edge\b", r"\bchlorophyll indices red edge\b", r"\bred edge chlorophyll indices\b"],
    "conservation success index": [r"\bconservation success index\b", r"\bconservation success indices\b"],
    "pacific decadal oscillation pdo index": [r"\bpacific decadal oscillation pdo index\b", r"\bdecadal oscillation pdo index\b", r"\bdecadal oscillation pdo indices\b"],
    "demographic vulnerability index": [r"\bdemographic vulnerability index\b", r"\bdemographic vulnerability indices\b"],
    "deprivation index": [r"\bdeprivation index\b", r"\bdeprivation indices\b"],
    "dynamic habitat index": [r"\bdynamic habitat index\b", r"\bdynamic habitat indices\b"],
    "dynamic range vegetation index": [r"\bdynamic range vegetation index\b", r"\bdynamic range vegetation indices\b"],
    "dynamic stress index": [r"\bdynamic stress index\b", r"\bdynamic stress indices\b"],
    "ecosystem index": [r"\becosystem index\b", r"\becosystem indices\b"],
    "enhanced vegetation index": [r"\benhanced vegetation index\b", r"\benhanced vegetation indices\b", r"\benhanced vegetation index 2\b", r"\bevi\b", r"\bevi2\b"],
    "fisher's alpha diversity index": [r"\bfisher s alpha diversity index\b", r"\bfisher alpha diversity index\b", r"\bfisher s alpha diversity indices\b"],
    "floating algae index": [r"\bfloating algae index\b", r"\bfloating algae indices\b"],
    "foliage height diversity index": [r"\bfoliage height diversity index\b", r"\bfoliage height diversity indices\b"],
    "forest condition index": [r"\bforest condition index\b", r"\bforest condition indices\b"],
    "forest integrity index": [r"\bforest integrity index\b", r"\bforest integrity indices\b"],
    "forest structural integrity index": [r"\bforest structural integrity index\b", r"\bforest structural integrity indices\b"],
    "fraction of photosynthetically active radiation": [r"\bfraction of photosynthetically active radiation\b", r"\bfpar\b"],
    "front probability index": [r"\bfront probability index\b", r"\bfront probability indices\b"],
    "fuel load index": [r"\bfuel load index\b", r"\bfuel load indices\b"],
    "functional diversity index": [r"\bfunctional diversity index\b", r"\bfunctional diversity indices\b"],
    "functional richness index": [r"\bindex of functional richness\b", r"\bfunctional richness index\b", r"\bfunctional richness indices\b"],
    "genetic vulnerability index": [r"\bgenetic vulnerability index\b", r"\bgenetic vulnerability indices\b"],
    "gini index": [r"\bgini index\b", r"\bgini indices\b"],
    "global development potential indices": [r"\bglobal development potential indices\b", r"\bglobal development potential index\b"],
    "global ecosystem restoration index": [r"\bglobal ecosystem restoration index\b", r"\bglobal ecosystem restoration indices\b"],
    "green chlorophyll vegetation index": [r"\bgreen chlorophyll vegetation index\b", r"\bgreen chlorophyll vegetation indices\b", r"\bgreen chlorophyll index\b"],
    "green normalized difference vegetation index": [r"\bgreen normalized difference vegetation index\b", r"\bgreen normalized difference vegetation indices\b"],
    "gross/net primary productivity": [r"\bgross primary productivity\b", r"\bnet primary productivity\b", r"\bprimary productivity\b"],
    "guild richness indices": [r"\bguild richness indices\b", r"\bguild richness index\b"],
    "habitat quality indices": [r"\bhabitat quality indices\b", r"\bhabitat quality index\b", r"\bhabitat health index\b"],
    "habitat reachability indices": [r"\bhabitat reachability indices\b", r"\bhabitat reachability index\b", r"\bhri\b"],
    "habitat suitability index": [r"\bhabitat suitability index\b", r"\bhabitat suitability indices\b"],
    "healthy coastal ecosystems (hce) indices": [r"\bhealthy coastal ecosystems hce\b", r"\bhce index\b", r"\bhealthy coastal ecosystems hce index\b"],
    "heat load index": [r"\bheat load index\b", r"\bheat load indices\b"],
    "human development index": [r"\bhuman development index\b", r"\bhuman development indices\b", r"\bhuman footprint index\b", r"\bhuman influence index\b",r"\bglobal human influence index\b", r"\bglobal human influence indices\b"],
    "jaccard index": [r"\bjaccard index\b", r"\bjaccard indices\b", r"\bjaccard dissimilarity\b"],
    "lacunarity indices": [r"\blacunarity indices\b", r"\blacunarity index\b", r"\bnormalized lacunarity index\b"],
    "landscape indices": [r"\blandscape indices\b", r"\blandscape index\b", r"\blandscape pattern indices\b", r"\blandscape connectivity indices\b"],
    "larvae noaa index": [r"\blarvae noaa index\b", r"\blarvae noaa indices\b", r"\blarvae index\b", r"\blarvae indices\b"],
    "leaf area index": [r"\bleaf area index\b", r"\bleaf area indices\b", r"\blai\b"],
    "living planet index": [r"\bliving planet index\b", r"\bliving planet indices\b"],
    "meris terrestrial chlorophyll index": [r"\bmeris terrestrial chlorophyll index\b", r"\bmeris terrestrial chlorophyll indices\b"],
    "modified chlorophyll absorption in reflectance index": [r"\bmodified chlorophyll absorption in reflectance index\b", r"\bmodified chlorophyll absorption in reflectance indices\b"],
    "disturbance index": [r"\bmodis derived disturbance index\b", r"\bmodis derived disturbance indices\b", r"\bdisturbance index\b", r"\bdisturbance indices\b"],
    "moment distance indices": [r"\bmoment distance indices\b", r"\bmoment distance index\b"],
    "mortality magnitude index": [r"\bmortality magnitude index\b", r"\bmortality magnitude indices\b"],
    "multivariate enso index": [r"\bmultivariate enso index\b", r"\bmultivariate enso indices\b", r"\benso index\b"],
    "nasa nature index": [r"\bnasa nature index\b", r"\bnasa nature indices\b"],
    "nasa sedac cropland expansion development potential index": [r"\bnasa sedac cropland expansion development potential index\b", r"\bnasa sedac cropland expansion development potential indices\b"],
    "nearest taxon index": [r"\bnearest taxon index\b", r"\bnearest taxon indices\b"],
    "net relatedness index": [r"\bnet relatedness index\b", r"\bnet relatedness indices\b"],
    "network centrality index": [r"\bnetwork centrality index\b", r"\bnetwork centrality indices\b", r"\bcentrality index\b"],
    "normalized burn ratio": [r"\bnormalized burn ratio\b", r"\bnormalized burn ratio 2\b"],
    "normalized difference chlorophyll index": [r"\bnormalized difference chlorophyll index\b", r"\bnormalized difference chlorophyll indices\b"],
    "normalized difference infrared index": [r"\bnormalized difference infrared index\b", r"\bnormalized difference infrared indices\b", r"\bndii5\b", r"\bndii6\b"],
    "normalized difference moisture index": [r"\bnormalized difference moisture index\b", r"\bnormalized difference moisture indices\b", r"\bndmi\b"],
    "normalized difference red edge": [r"\bnormalized difference red edge\b"],
    "normalized difference snow index": [r"\bnormalized difference snow index\b", r"\bnormalized difference snow indices\b", r"\bdynamic snow cover indices\b", r"\bndsi\b"],
    "normalized difference vegetation index": [r"\bnormalized difference vegetation index\b", r"\bnormalized difference vegetation indices\b", r"\bndvi\b"],
    "normalized water index": [r"\bnormalized water index\b", r"\bnormalized water indices\b", r"\bnwi\b"],
    "normalized wilt index": [r"\bnormalized wilt index\b", r"\bnormalized wilt indices\b"],
    "northern oscillation index": [r"\bnorthern oscillation index\b", r"\bnorthern oscillation indices\b"],
    "orographic uplift index": [r"\borographic uplift index\b", r"\borographic uplift indices\b"],
    "palmer drought severity index": [r"\bpalmer drought severity index\b", r"\bpalmer drought severity indices\b", r"\bdrought index\b", r"\bpalmer drought index\b", r"\bpdsi\b"],
    "photochemical reflectance index": [r"\bphotochemical reflectance index\b", r"\bphotochemical reflectance indices\b"],
    "phylogenetic diversity index": [r"\bphylogenetic diversity index\b", r"\bphylogenetic diversity indices\b"],
    "physical complexity index": [r"\bphysical complexity index\b", r"\bphysical complexity indices\b"],
    "plant area index": [r"\bplant area index\b", r"\bplant area indices\b"],
    "plant senescence reflectance index": [r"\bplant senescence reflectance index\b", r"\bplant senescence reflectance indices\b"],
    "rao's q index": [r"\brao s q\b", r"\brao s q index\b", r"\brao s q indices\b"],
    "red edge ndvi": [r"\bred edge ndvi\b"],
    "red edge position index": [r"\bred edge position index\b", r"\bred edge position indices\b"],
    "red list indices": [r"\bred list indices\b", r"\bred list index\b"],
    "renormalized difference vegetation index": [r"\brenormalized difference vegetation index\b", r"\brenormalized difference vegetation indices\b"],
    "rewilding index": [r"\brewilding index\b", r"\brewilding indices\b"],
    "shannon's diversity index": [r"\bshannon s diversity index\b", r"\bshannon diversity index\b", r"\bshannon s diversity indices\b", r"\bshannon index\b"],
    "simpson's index of diversity": [r"\bsimpson s index of diversity\b", r"\bsimpson s indices of diversity\b", r"\bsimpson s index\b", r"\bsimpson s evenness index\b"],
    "soil moisture index": [r"\bsoil wetness index\b", r"\bsoil wetness indices\b", r"\bsoil moisture vegetation indices\b", r"\bsoil moisture index\b", r"\bsoil adjusted vegetation index\b", r"\bsavi\b"],
    "sorensen's index": [r"\bsorensen s index\b", r"\bsorensen s indices\b"],
    "species attractiveness index": [r"\bspecies attractiveness index\b", r"\bspecies attractiveness indices\b"],
    "species habitat index": [r"\bspecies habitat index\b", r"\bspecies habitat indices\b"],
    "species protected index": [r"\bspecies protected index\b", r"\bspecies protected indices\b"],
    "species status information index": [r"\bspecies status information index\b", r"\bspecies status information indices\b"],
    "spectral heterogeneity indices": [r"\bspectral heterogeneity indices\b", r"\bspectral heterogeneity index\b"],
    "srtm continuous heat-insolation load index (chili)": [r"\bsrtm continuous heat insolation load index\b", r"\bsrtm continuous heat insolation load indices\b"],
    "standardized precipitation index": [r"\bstandardized precipitation index\b", r"\bstandardized precipitation indices\b"],
    "structural complexity index": [r"\bstructural complexity index\b", r"\bstructural complexity indices\b"],
    "structure insensitive pigment index": [r"\bstructure insensitive pigment index\b", r"\bstructure insensitive pigment indices\b"],
    "sustainable fisheries and aquaculture (sfa) indices": [r"\bsustainable fisheries and aquaculture sfa indices\b", r"\bsustainable fisheries and aquaculture sfa index\b"],
    "synchrony index": [r"\bsynchrony index\b", r"\bsynchrony indices\b"],
    "tassel cap indices": [r"\btassel cap indices\b", r"\btassel cap index\b", r"\btassel cap transformation\b"],
    "temperature condition index": [r"\btemperature condition index\b", r"\btemperature condition indices\b"],
    "temperature vulnerability index": [r"\btemperature vulnerability index\b", r"\btemperature vulnerability indices\b"],
    "temporal structural heterogeneity index": [r"\btemporal structural heterogeneity index\b", r"\btemporal structural heterogeneity indices\b"],
    "terrain indices": [r"\bterrain indices\b", r"\bterrain index\b", r"\bterrain roughness index\b", r"\bterrain ruggedness index\b"],
    "thermal indices": [r"\bthermal indices\b", r"\bthermal index\b"],
    "topographic convergence index": [r"\btopographic convergence index\b", r"\btopographic convergence indices\b"],
    "topographic indices": [r"\btopographic indices\b", r"\btopographic index\b"],
    "topographic position index": [r"\btopographic position index\b", r"\btopographic position indices\b"],
    "topographic solar radiation index": [r"\btopographic solar radiation index\b", r"\btopographic solar radiation indices\b"],
    "topographic wetness index": [r"\btopographic wetness index\b", r"\btopographic wetness indices\b"],
    "tree canopy cover": [r"\btree canopy cover\b"],
    "triangular vegetation index": [r"\btriangular vegetation index\b", r"\btriangular vegetation indices\b"],
    "urbaness index": [r"\burbaness index\b", r"\burbaness indices\b"],
    "vegetation condition index": [r"\bvegetation condition index\b", r"\bvegetation condition indices\b"],
    "vegetation continuous fields": [r"\bvegetation continuous fields\b", r"\bvcf\b"],
    "vegetation health index": [r"\bvegetation health index\b", r"\bvegetation health indices\b"],
    "vegetation thermal stress index": [r"\bvegetation thermal stress index\b", r"\bvegetation thermal stress indices\b"],
    "visible atmospherically resistant index": [r"\bvisible atmospherically resistant index\b", r"\bvisible atmospherically resistant indices\b"],
    "vulnerability index": [r"\bvulnerability index\b", r"\bvulnerability indices\b"],
    "water quality indices": [r"\bwater quality indices\b", r"\bwater quality index\b"],
    "water stress index": [r"\bwater stress index\b", r"\bwater stress indices\b"],
    "wetness and roughness indices": [r"\bwetness and roughness indices\b", r"\bwetness and roughness index\b"],
    "wetness ruggedness dem index": [r"\bwetness ruggedness dem index\b", r"\bwetness ruggedness dem indices\b"],
}
